import type { Metadata } from "next"
import "./globals.css"

// Font Family
import { Azeret_Mono, Anton } from "next/font/google"

// Components
import Navbar from "@/components/navigation/Navbar"

const AzeretMonoFont = Azeret_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-azeret-mono",
})

const AntonFont = Anton({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-anton",
})

export const metadata: Metadata = {
  title: "PORTFOLIO",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={`${AzeretMonoFont.variable} ${AntonFont.variable} antialiased`}
    >
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  )
}